trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: ExpoBuild
  displayName: 'Expo Build Job'
  steps:
  - checkout: self

  - task: NodeTool@0
    inputs:
      versionSource: 'spec'
      versionSpec: '19.x'
      checkLatest: true

  - script: yarn install
    displayName: 'Install dependencies'

  - script: |
      npm install -g pnpm
      pnpm version
    displayName: 'Install pnpm'

  - script: |
      pnpm run lint
    displayName: 'Run lint'

  - script: |
      npm install -g eas-cli@latest
      yarn global add eas-cli
    displayName: 'Install EAS CLI'

  - script: |
      if [ "$(Build.Reason)" == "PullRequest" ]; then
        EXPO_TOKEN=$(EXPO_TOKEN) eas build --platform android --profile preview --non-interactive
      else
        EXPO_TOKEN=$(EXPO_TOKEN) eas build --platform android --profile production --non-interactive
      fi
    displayName: 'Build with EAS CLI'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)/build'
      Contents: '**/*.apk'  # Adjust the pattern according to your artifact's extension
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'android-build'
      publishLocation: 'Container'
