trigger:
  branches:
    include:
    - '*'  # Trigger on all branches for builds

pr:  # Trigger on pull request events for preview builds
  branches:
    include:
    - '*'  # Trigger on PRs targeting all branches

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: ExpoBuild
  displayName: 'Expo Build Job'
  steps:
  - checkout: self

# <<<<<<< HEAD
#   - name: Install NVM
#     run: |
#       curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
#       export NVM_DIR="$HOME/.nvm"
#       [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
#       [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
# =======
#   - script: |
#       nvm install 18.x
#       nvm use 18.x
#     displayName: 'Set up Node'
  - task: NodeTool@0
    inputs:
      versionSource: 'spec'
      versionSpec: '18.x'
      checkLatest: true
  - script: yarn install
    displayName: 'Install dependencies'

  # Expo EAS CLI installation
  - script: |
     npm install -g expo-cli
          expo publish --token $(dlOpfJe4FTyEZGfQmqMM1KS6Sjw8jCgdoIYF01QS)
        displayName: 'Publish Expo project'
  # Run tests (if applicable)
  # - script: yarn run test
  #   displayName: 'Run tests'

  # Expo EAS build
  - script: |
      if [ "$(Build.Reason)" == "PullRequest" ]; then
        eas build --platform all --profile preview --non-interactive
      else
        eas build --platform all --profile production --non-interactive
      fi
    displayName: 'Build with EAS CLI'

  # Post-build steps (e.g., handling artifacts, notifications)
  # Custom scripts or tasks can be added here.

# Additional configurations like environment variables, secrets, and post-build actions should be adjusted according to your project requirements.
